---
- name: Create a security group
  local_action:
    module: ec2_group
    name: "{{ security_group_name }}"
    description: "{{ security_group_description }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    rules: "{{ security_group_rules | from_yaml }}"
    rules_egress: "{{ security_group_rules_egress | from_yaml }}"
  register: created_security_group
- set_stats:
    data:
      created_security_group: "{{ created_security_group }}"
