---
- name: Add Instance(s) names with index suffix, if there is more than 1 Instance
  local_action:
    module: ec2_tag
    resource: "{{ item.id }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "{{ instance_name }}__{{ index }}"
  loop: "{{ created_instances.instances }}"
  loop_control:
    index_var: index
  when: instance_name is defined and instance_name != '' and created_instances.instances | length > 1
- name: Add tags to Instance(s)
  local_action:
    module: ec2_tag
    resource: "{{ item.id }}"
    region: "{{ region }}"
    state: present
    tags: "{{ instance_tags | from_yaml }}"
  with_items: "{{ created_instances.instances }}"
- name: Add tags to Instance(s) with index suffix
  include: add_indexed_tags.yml
  loop: "{{ created_instances.instances }}"
  loop_control:
    loop_var: outer_item
    index_var: outer_index


